### ISSUE TITLE
Clean container content

### ISSUE THREAD

**Issue by tsafin** [intersystems-ru/CPM#22]
As we have discovered the container .tgz geerated by `npm publish` contains not only package.json and referenced via path: file, but all files which happen to be in the directory at the moment.

We need before exporting to create new package-specific staging area and make sure there is only xml container geneated and metainfo file.

**Comment by daimor** [comment]
we can use .npmignore file, to ignore some files, and npm supports prebuild scripts as well.

**Comment by tsafin** [comment]
Fixed/worked-around by da6236ba179307b1823a9969dcf241a95dd5b058 in the branch.
