### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/CPM#6]
Is the project usable now? If it is, could you please add a bit of installation and usage details (short how-to description) into README.md file?

**Comment by tsafin** [comment]
Sorry, Nikita, it's not useable now - once we complete most checkboxes in README.md we will be ready  and not hesitate to announce.
Right now it's work in progress (with plan to have anything before GS) so we appreciate any help if you want to.

**Comment by ZitRos** [comment]
Thank you for the answer!

CPM project is the project I am interested in. I want just to decide do I need to develop an installer for Caché WEB terminal or Light pivot table projects to make them easy to install and use in close future. The namespace mapping (f.e. %All) and "global installation" (%SYS) is the features I need to involve to my project. Will CPM replace this issues? I mean, will the perspective of CPM project be able to replace %Installer class functionality and get totally simple as "one-command-to-install"?

**Comment by tsafin** [comment]
Yes, that's exactly rhe case which each package manager supposed to
address: packaging, installing (and deinstalling)

http://about.me/timur.safin

2015-02-10 19:52 GMT+03:00 Nikita <notifications@github.com>:

**Comment by tsafin** [comment]
Discussed this issue offline
