### ISSUE TITLE
Add CPM.SourceTypes.inc

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/CPM#7]
Referred to in https://github.com/intersystems-ru/CPM/blob/master/CPM/SourceType/IBase.cls.xml#L4

**Comment by tsafin** [comment]
Thanks for this report - fixed by 1fb3b964ca31bba8ba0faa9bcb373411a7201132 in pakage_xml branch, and will lend to trunk once passed code review

**Comment by tsafin** [comment]
Landed to the master
